name: el2nm
channels:
  - defaults
dependencies:
  - cudatoolkit=11.3
  - torchvision
   - torchaudio
  - pytorch
  - ipython
  - nb_conda
  - matplotlib
  - scipy
  - opencv
  - scikit-image
  - pandas
  - scikit-learn
   - lpips
  - yacs
