data:
    image_size: 128
    channels: 3
    num_workers: 0
    train_data_dir: "/raid/qinjiahao/data/Sony/"  # path to directory of train data
    test_data_dir: '/raid/qinjiahao/data/Sony/'  # path to directory of test data
    test_save_dir: '/raid/qinjiahao/data/result/'   # path to directory of saving restored data
    val_save_dir: '/raid/qinjiahao/data/Sony/validation/'
    grid_r: 16
    conditional: True


model:
    in_channels: 3
    out_ch: 3
    ch: 128
    ch_mult: [1, 2, 3, 4]
    num_res_blocks: 2
    attn_resolutions: [16, ]
    dropout: 0.0
    ema_rate: 0.999
    ema: True
    resamp_with_conv: True

diffusion:
    beta_schedule: linear
    beta_start: 0.0001
    beta_end: 0.02
    num_diffusion_timesteps: 300


training:
    patch_n: 16
    batch_size: 1
    n_epochs: 2000
    n_iters: 2000000
    snapshot_freq: 1000  # model save frequency
    validation_freq: 10000
    resume: '/raid/qinjiahao/projects/starlight_denoising/saved_models/ddpm_model/context_star_gauss_2_clear'  # path to pretrained model
    best_resume: '/raid/qinjiahao/projects/starlight_denoising/saved_models/ddpm_model/context_best_2_clear'  # path to pretrained model
    seed: 61  # random seed

sampling:
    batch_size: 1
    last_only: True
    sampling_timesteps: 25

optim:
    weight_decay: 0.0001
    optimizer: "Adam"
    lr: 0.00001
    amsgrad: False
    eps: 0.00000001
